### ISSUE TITLE
Added French and English to mapping.html. Problem: Greek!

### ISSUE THREAD

**Issue by pverkind** [djbpitt/tufts_2018#6]
Dear all, 

Paul and I added the French and English texts to mapping.html. 
However, the Greek treetagger files are empty; and the exmaralda files don't have any annotations in them.

Should we ask Thomas if something went wrong there?

Best, 

Peter

**Comment by pverkind** [comment]
Dear all, 

We just found out that the problem is that the Greek group did not make sentence annotations. 
(see https://korpling.org/annis3/#_q=dG9rCg&_c=TkVIZXJic19HcmVla192MS4w&cl=5&cr=5&s=0&l=10)

Best, 

Peter and Paul

**Comment by djbpitt** [comment]
Anke and I discussed this. We decided that we should omit the Greek text from the edition unless they give us content we can work with with a reasonable amount of time for us to work with it. Let's leave a place for it for now and concentrate on the other versions.

**Comment by djbpitt** [comment]
Resolved
